#*******************************************************************************************************
#Accueil************************************************************************************************
#*******************************************************************************************************

hotel_accueil:
    pattern: /{_locale}
    defaults: { _controller: BittichHotelBundle:Accueil:index, _locale: fr }
    requirements:
      _locale: fr|en

hotel_accueil_commenter:
    pattern: /{_locale}/commentaires
    defaults: { _controller: BittichHotelBundle:Accueil:commenter, _locale: fr }
    requirements:
      _locale: fr|en
#*******************************************************************************************************
#Tarif**************************************************************************************************
#*******************************************************************************************************

hotel_tarif_lister:
    pattern: /{_locale}/tarif/liste
    defaults: { _controller: BittichHotelBundle:Tarif:lister, _locale: fr }
    requirements:
      _locale: fr|en
      
      

hotel_tarif_ajouter:
    pattern: /{_locale}/admin/tarif/ajouter
    defaults: { _controller: BittichHotelBundle:Tarif:editer, _locale: fr }
    requirements:
      _locale: fr|en
      id: \d+

hotel_tarif_editer:
    pattern: /{_locale}/admin/tarif/editer/{id}
    defaults: { _controller: BittichHotelBundle:Tarif:editer, _locale: fr }
    requirements:
      _locale: fr|en
      id: \d+
      
hotel_tarif_supprimer:
    pattern: /{_locale}/admin/tarif/supprimer/{id}
    defaults: { _controller: BittichHotelBundle:Tarif:supprimer, _locale: fr }
    requirements:
      _locale: fr|en
      id: \d+

#*******************************************************************************************************
#Modele*************************************************************************************************
#*******************************************************************************************************

hotel_modele_lister:
    pattern: /{_locale}/modele/liste
    defaults: { _controller: BittichHotelBundle:Modele:lister, _locale: fr }
    requirements:
      _locale: fr|en

hotel_modele_ajouter:
    pattern: /{_locale}/employe/modele/ajouter
    defaults: { _controller: BittichHotelBundle:Modele:editer, _locale: fr }
    requirements:
      _locale: fr|en
      id: \d+

hotel_modele_editer:
    pattern: /{_locale}/employe/modele/editer/{id}
    defaults: { _controller: BittichHotelBundle:Modele:editer, _locale: fr }
    requirements:
      _locale: fr|en
      id: \d+
      
hotel_modele_supprimer:
    pattern: /{_locale}/employe/modele/supprimer/{id}
    defaults: { _controller: BittichHotelBundle:Modele:supprimer, _locale: fr }
    requirements:
      _locale: fr|en
      id: \d+
      
#*******************************************************************************************************
#Chambre************************************************************************************************
#*******************************************************************************************************

hotel_chambre_lister:
    pattern: /{_locale}/chambre/liste/{page}
    defaults: { _controller: BittichHotelBundle:Chambre:lister, _locale: fr, page: 1 }
    requirements:
      _locale: fr|en
      page: \d+
hotel_chambre_ajouter:
    pattern: /{_locale}/employe/chambre/ajouter
    defaults: { _controller: BittichHotelBundle:Chambre:editer, _locale: fr }
    requirements:
      _locale: fr|en
      id: \d+

hotel_chambre_editer:
    pattern: /{_locale}/employe/chambre/editer/{id}
    defaults: { _controller: BittichHotelBundle:Chambre:editer, _locale: fr }
    requirements:
      _locale: fr|en
      id: \d+
      
hotel_chambre_supprimer:
    pattern: /{_locale}/employe/chambre/supprimer/{id}
    defaults: { _controller: BittichHotelBundle:Chambre:supprimer, _locale: fr }
    requirements:
      _locale: fr|en
      id: \d+
      
#*******************************************************************************************************
#Calendrier*********************************************************************************************
#*******************************************************************************************************

hotel_calendrier_lister:
    pattern: /{_locale}/calendrier/liste/{page}
    defaults: { _controller: BittichHotelBundle:Calendrier:lister, _locale: fr,page: 1 }
    requirements:
      _locale: fr|en
      page: \d+

hotel_calendrier_ajouter:
    pattern: /{_locale}/employe/calendrier/ajouter
    defaults: { _controller: BittichHotelBundle:Calendrier:editer, _locale: fr }
    requirements:
      _locale: fr|en
      id: \d+

hotel_calendrier_editer:
    pattern: /{_locale}/employecalendrier/editer/{id}
    defaults: { _controller: BittichHotelBundle:Calendrier:editer, _locale: fr }
    requirements:
      _locale: fr|en
      id: \d+
      
hotel_calendrier_supprimer:
    pattern: /{_locale}/employe/calendrier/supprimer/{id}
    defaults: { _controller: BittichHotelBundle:Calendrier:supprimer, _locale: fr }
    requirements:
      _locale: fr|en
      id: \d+
 
hotel_calendrier_addrange:
      pattern: /{_locale}/employe/calendrier/ajouter-dates
      defaults: { _controller: BittichHotelBundle:Calendrier:addrange, _locale: fr }
      requirements:
        _locale: fr|en
      options:
          expose: true
#*******************************************************************************************************
#Prix***************************************************************************************************
#*******************************************************************************************************

hotel_prix_lister:
    pattern: /{_locale}/prix/liste
    defaults: { _controller: BittichHotelBundle:Prix:lister, _locale: fr }
    requirements:
      _locale: fr|en

hotel_prix_ajouter:
    pattern: /{_locale}/admin/prix/ajouter
    defaults: { _controller: BittichHotelBundle:Prix:editer, _locale: fr }
    requirements:
      _locale: fr|en
      id: \d+

hotel_prix_editer:
    pattern: /{_locale}/admin/prix/{idmodele}-{idtarif}
    defaults: { _controller: BittichHotelBundle:Prix:editer, _locale: fr }
    requirements:
      _locale: fr|en
      id: \d+
      
hotel_prix_supprimer:
    pattern: /{_locale}/admin/prix/supprimer/{idmodele}-{idtarif}
    defaults: { _controller: BittichHotelBundle:Prix:supprimer, _locale: fr }
    requirements:
      _locale: fr|en
      id: \d+
  
#*******************************************************************************************************
#Réservation********************************************************************************************
#*******************************************************************************************************
      
hotel_reservation_lister:
    pattern: /{_locale}/reservation/liste/{page}
    defaults: { _controller: BittichHotelBundle:Reservation:lister, _locale: fr, page: 1 }
    requirements:
      _locale: fr|en
      page: \d+

hotel_reservation_lister_client:
    pattern: /{_locale}/reservation/liste-client/{page}
    defaults: { _controller: BittichHotelBundle:Reservation:listereservation, _locale: fr, page: 1 }
    requirements:
      _locale: fr|en
      page: \d+
hotel_reservation_ajouter:
    pattern: /{_locale}/reservation/ajouter
    defaults: { _controller: BittichHotelBundle:Reservation:editer, _locale: fr }
    requirements:
      _locale: fr|en
      id: \d+

hotel_reservation_editer:
    pattern: /{_locale}/reservation/editer/{id}
    defaults: { _controller: BittichHotelBundle:Reservation:editer, _locale: fr }
    requirements:
      _locale: fr|en
      id: \d+
      
hotel_reservation_supprimer:
    pattern: /{_locale}/reservation/supprimer/{id}
    defaults: { _controller: BittichHotelBundle:Reservation:supprimer, _locale: fr }
    requirements:
      _locale: fr|en
      id: \d+
      
#hotel_reservation_nouveau:
 #   pattern: /{_locale}/reservation/nouveau
  #  defaults: { _controller: BittichHotelBundle:Reservation:nouveau, _locale: fr }
   # requirements:
    #  _locale: fr|en
     # id: \d+ 
#hotel_reservation_nouvelle:
 #   pattern: /{_locale}/reservation/nouvelle-reservation/{id}
  #  defaults: { _controller: BittichHotelBundle:Reservation:nouvelleReservation, _locale: fr}
   # requirements:
    #  _locale: fr|en
     # id: \d+    
hotel_reservation_confirm:
    pattern: /{_locale}/reservation/confirm
    defaults: { _controller: BittichHotelBundle:Reservation:confirm, _locale: fr, _format: json}
    requirements:
      _locale: fr|en
    options:
      expose: true   
hotel_reservation_search:
    pattern: /{_locale}/reservation/search
    defaults: { _controller: BittichHotelBundle:Reservation:search, _locale: fr, _format: json}
    requirements:
      _locale: fr|en
    options:
      expose: true 
      #* expose = true, pour générer la route en javascript (fosjsbundle) *#
      

#*******************************************************************************************************
#SuperAdmin*********************************************************************************************
#*******************************************************************************************************

hotel_admin_lister:
    pattern: /{_locale}/admin/utilisateur/liste/{page}
    defaults: { _controller: BittichHotelBundle:Admin:lister, _locale: fr, page: 1 }
    requirements:
      _locale: fr|en   
      page: \d+
      
hotel_admin_lister_role:
    pattern: /{_locale}/admin/liste-role/{role}/{page}
    defaults: { _controller: BittichHotelBundle:Admin:listerrole, _locale: fr, page: 1 }
    requirements:
      _locale: fr|en  
      page: \d+
         
#hotel_admin_accueil:
 #   pattern:  /{_locale}/admin/accueil.html
  #  defaults: { _controller: BittichHotelBundle:Admin:index, _locale: fr }
   # requirements:
    #      _locale: fr|en  

hotel_admin_rechercher:
    pattern: /{_locale}/admin/rechercher
    defaults: { _controller: BittichHotelBundle:Admin:recherchenom, _locale: fr}
    requirements:
           _method: POST|GET
           _locale: fr|en   

hotel_admin_promote:
    pattern:  /{_locale}/admin/promouvoir/{id}
    defaults: { _controller: BittichHotelBundle:Admin:promote, _locale: fr }
    requirements:
        id: \d+   
        _locale: fr|en   

hotel_admin_demote:
    pattern:  /{_locale}/admin/retrograder/{id}
    defaults: { _controller: BittichHotelBundle:Admin:demote, _locale: fr }
    requirements:
        id: \d+   
        _locale: fr|en   

hotel_admin_desactiver:
    pattern:  /{_locale}/admin/desactiver/{id}
    defaults: { _controller: BittichHotelBundle:Admin:desactivate, _locale: fr }
    requirements:
        id: \d+   
        _locale: fr|en  

hotel_admin_activer:
    pattern:  /{_locale}/admin/reactiver/{id}
    defaults: { _controller: BittichHotelBundle:Admin:reactivate, _locale: fr }
    requirements:
        id: \d+   
        _locale: fr|en  
        
