parameters:
#    bittich_hotel.example.class: Bittich\HotelBundle\Example

services:
#    bittich_hotel.example:
#        class: %bittich_hotel.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    bitti_hotel.registration.form.type:
        class: Bittich\HotelBundle\Form\Type\UserType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: bittich_hotelebundle_usertyp }
