<?php

namespace Bittich\HotelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CalendrierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendrierRepository extends EntityRepository
{

        //pour ne faire qu'une seule requete (jointure)
    public function getCalendrierAvecTarif() {
        $qb = $this->createQueryBuilder('a')
                ->leftJoin('a.tarif', 't')
                ->leftJoin('a.chambres', 'c')
                ->addSelect('t')
                ->addSelect('c')
                ->orderBy('a.datej','ASC');
        return $qb->getQuery()
                  ->getResult();
    }
}
