<?php
namespace Bittich\HotelBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ChambreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChambreRepository extends EntityRepository {
    //pour ne faire qu'une seule requete (jointure)
    public function getChambreAvecModele() {
        $qb = $this->createQueryBuilder('a')
                ->leftJoin('a.modele', 'm')
                ->leftJoin('a.disponibilites','d')
                ->addSelect('d')
                ->addSelect('m');

        return $qb->getQuery()
                  ->getResult();
    }

}
