<?php

namespace Bittich\HotelBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ChambreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChambreRepository extends EntityRepository {

   

    //pour ne faire qu'une seule requete (jointure)
    public function getChambre() {
        $qb = $this->createQueryBuilder('a')
                ->leftJoin('a.modele', 'm')
                ->leftJoin('a.disponibilites', 'd')
                ->addSelect('d')
                ->addSelect('m');

        return $qb->getQuery()
                        ->getResult();
    }
    
    public function pagine($nombreParPage, $page) {
        $qb = $this->createQueryBuilder('a')
                ->leftJoin('a.modele', 'm')
                ->leftJoin('a.disponibilites', 'd')
                ->addSelect('d')
                ->addSelect('m');

        $qb->setFirstResult(($page - 1) * $nombreParPage)
                ->setMaxResults($nombreParPage);
        return new Paginator($qb);
    }

}
