<?php

namespace Bittich\HotelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PrixRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrixRepository extends EntityRepository {

    public function getPrixComplet() {
        $qb = $this->createQueryBuilder('p')
                ->leftJoin('p.modele', 'm')
                ->leftJoin('p.tarif', 't')
                ->addSelect('m')
                ->addSelect('t')
                ->orderBy('t.couleur', 'ASC');
        return $qb->getQuery()
                        ->getResult();
    }
        public function findPrix($idmodele,$idtarif) {
        $qb = $this->createQueryBuilder('p')
                ->leftJoin('p.modele', 'm')
                ->leftJoin('p.tarif', 't')
                ->andWhere('m.id = :idmodele')
                ->andWhere('t.id = :idtarif')
                ->addSelect('m')
                ->addSelect('t')
                ->setParameter('idmodele' , $idmodele)
                ->setParameter('idtarif' , $idtarif);
        
        return $qb->getQuery()->getOneOrNullResult();
                       
    }

}
