<?php

namespace Bittich\HotelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends EntityRepository {

    public function findByUser($iduser) {
        $qb = $this->createQueryBuilder('p')
                ->leftJoin('p.client', 'u')
                ->andWhere('u.id = :iduser')
                ->addSelect('u')
                ->setParameter('iduser', $iduser);

        return $qb->getQuery()->getResult();
                }

}
