parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: hotel
    database_user: root
    database_password: 
    mailer_transport: gmail
    mailer_host: ~
    mailer_user: komintern1988
    mailer_password: kikoolol
    locale: fr
    secret: 99910888cb764a3f4c14e2c4a5ace939b
    database_path: null
