bittich_user:
    resource: "@BittichUserBundle/Resources/config/routing.yml"
    prefix:   /

bittich_hotel_locale:
    resource: "@BittichHotelBundle/Resources/config/routing.yml"
    prefix:   /
