#*******************************************************************************************************
#FOS_USER_BUNDLE****************************************************************************************
#*******************************************************************************************************

fos_user_security:
    resource: "routing/security.xml"
    prefix: /{_locale}

fos_user_profile:
    resource: "routing/profil.xml"
    prefix: /{_locale}/compte

fos_user_register:
    resource: "routing/inscription.xml"
    prefix: /{_locale}/inscription

fos_user_resetting:
    resource: "routing/resetting.xml"
    prefix: /{_locale}/resetting

fos_user_change_password:
    resource: "routing/modifier_mot_de_passe.xml"
    prefix: /{_locale}/compte
    
