<?php

namespace Bittich\HotelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrixRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrixRepository extends EntityRepository
{
}
