<?php

namespace Bittich\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TarifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

    public function findUserByRole($role) {
        $qb = $this->createQueryBuilder('u')
                ->andWhere('u.roles LIKE :role')
                ->setParameter('role', '%' . $role . '%')
                ->orderBy('u.nom', 'ASC');
        return $qb->getQuery()
                        ->getResult();
    }

    public function findUserByNomPrenom($motcle) {
        $qb = $this->createQueryBuilder('u')
                ->andWhere('u.nom LIKE :motcle OR u.prenom LIKE :motcle')
                ->setParameter('motcle', '%' . $motcle . '%')
                ->orderBy('u.nom', 'ASC');
        return $qb->getQuery()
                        ->getResult();
    }

}
